
language: php

sudo: false

dist: trusty

matrix:
  include:
   - php: 5.3
     dist: precise
   - php: 5.4
   - php: 5.5
   - php: 5.6
   - php: 7.0
   - php: 7.1
   - php: 7.2
  fast_finish: true

services:
  - memcached
  - mysql

before_script:
    - if [ ${TRAVIS_PHP_VERSION:0:3} != "5.2" ]; then travis_retry composer --prefer-source --dev install; fi
    - if [ ${TRAVIS_PHP_VERSION:0:3} <= "5.6" ]; then  phpenv config-add travis.ini; fi
    - if [ ${TRAVIS_PHP_VERSION:0:3} >= "5.3" ]; then  phpenv config-add error_reporting.ini; fi
    - if [[ $TRAVIS_PHP_VERSION = 7.* ]]; then  composer require phpunit/phpunit 6.4.1; fi
    - mysql -e "create database IF NOT EXISTS test;" -uroot

before_install:
    - phpenv config-rm xdebug.ini || return 0

install:
    - travis_retry composer install
    - git clone --depth=50 --branch=master git://github.com/smarty-php/smarty-phpunit.git

script:
   - cd smarty-phpunit
   - if [[ $TRAVIS_PHP_VERSION = 7.* ]]; then
        ../vendor/bin/phpunit ./;
    else
        phpunit ./;
    fi

