version: "2"
services:
  base:
    build:
      context: .
      dockerfile: ./utilities/testrunners/php72/Dockerfile
    volumes:
      - smarty-code:/app
    working_dir: /app
  php72:
    extends:
      service: base
    build:
      dockerfile: ./utilities/testrunners/php72/Dockerfile
  php73:
    extends:
      service: base
    build:
      dockerfile: ./utilities/testrunners/php73/Dockerfile
  php74:
    extends:
      service: base
    build:
      dockerfile: ./utilities/testrunners/php74/Dockerfile
  php80:
    extends:
      service: base
    build:
      dockerfile: ./utilities/testrunners/php80/Dockerfile
  php81:
    extends:
      service: base
    build:
      dockerfile: ./utilities/testrunners/php81/Dockerfile
  php82:
    extends:
      service: base
    build:
      dockerfile: ./utilities/testrunners/php82/Dockerfile
  php83:
    extends:
      service: base
    build:
      dockerfile: ./utilities/testrunners/php83/Dockerfile
volumes:
  smarty-code:

x-mutagen:
  sync:
    defaults:
      symlink:
        mode: "posix-raw"
      ignore:
        vcs: true
        paths:
          - ".docker"
          - ".env.docker"
          - ".bundles"
          - "docker-compose.yml"
          - ".idea"
          - ".DS_Store"
      mode: "two-way-resolved"
      configurationBeta:
        permissions:
          defaultOwner: "id:${APP_USER_ID}"
          defaultGroup: "id:${APP_GROUP_ID}"
          defaultFileMode: 0666
          defaultDirectoryMode: 0755
      permissions:
        defaultOwner: "id:${APP_USER_ID}"
        defaultGroup: "id:${APP_GROUP_ID}"
    smarty-code:
      alpha: "."
      beta: "volume://smarty-code"

